In [68]:
import skimage
from skimage import io
image = skimage.io.imread(fname = "D://OneDrive//Git_proj//NumpyCNN//WechatIMG1994.jpeg")

image = skimage.color.rgb2gray(image)
print(image)

[[0.12392157 0.12392157 0.12392157 ... 0.08284314 0.08284314 0.08284314]
 [0.12392157 0.12392157 0.12392157 ... 0.08284314 0.08284314 0.08284314]
 [0.12392157 0.12392157 0.12392157 ... 0.08284314 0.08284314 0.08284314]
 ...
 [0.08257529 0.07865373 0.07865373 ... 0.10236784 0.10236784 0.10236784]
 [0.08340863 0.08257529 0.07865373 ... 0.10236784 0.10236784 0.10236784]
 [0.08340863 0.08257529 0.07865373 ... 0.10236784 0.10236784 0.10236784]]


In [36]:
skimage.io.imsave(fname = "D://OneDrive//Git_proj//NumpyCNN//test.jpeg", arr = image)

Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.


In [37]:
import numpy as np
l1_filter = np.zeros((2,3,3))
print(l1_filter)
l1_filter[0,:,:] = np.array([[[-1,0,1],
                              [-1,0,1],
                              [-1,0,1]]])
l1_filter[1,:,:] = np.array([[[1,1,1],
                              [0,0,0],
                              [-1,-1,-1]]])
print(l1_filter.shape[2])

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3


In [38]:
import skimage.data
img = skimage.io.imread(fname = "D://OneDrive//Git_proj//NumpyCNN//WechatIMG1994.jpeg")

img = skimage.color.rgb2gray(img)
print(img.shape)

(640, 1024)


In [39]:
a = np.arange(3/2, 7/2)
print ('原始数组：')
print (a)

原始数组：
[1.5 2.5]


In [40]:
a = np.arange(3/2.0, 7/2.0)
print ('原始数组：')
print (a)

原始数组：
[1.5 2.5]


In [41]:
a = np.uint16(np.arange(3/2.0, 7/2.0))
print ('原始数组：')
print (a)

原始数组：
[1 2]


In [42]:
np.floor(3/2.0)

1.0

In [43]:
np.uint16(np.floor(3/2.0))

1

In [44]:
np.ceil(3/2.0)

2.0

In [84]:
curr_region = [[[-1, 0, 1], 
                [-1, 0, 1], 
                [-1, 0, 1]],
                [[-1, 0, 1], 
                [-1, 0, 1], 
                [-1, 0, 1]]]

im2col = np.zeros((3,9))
print(im2col)
print(len(curr_region))
   
print(im2col)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2


TypeError: list indices must be integers or slices, not tuple

In [27]:
len(curr_region)

3

In [ ]:
curr_region = [[-1, 0, 1], 
                [-1, 0, 1], 
                [-1, 0, 1]]
im2col = np.zeros((img.shape[0]-filter_size+1,img.shape[1]-filter_size+1))
print(im2col)
temp = []
for i in range(len(curr_region)):
    temp += curr_region[i]
im2col[0] = temp
print(im2col)

In [61]:
len(image.shape)

2

In [69]:
feature_maps = np.zeros((2, 5, 5))
print(feature_maps)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [76]:
conv_filter = np.zeros((2,3,3))
conv_filter[0, :, :] = np.array([[[-1, 0, 1], 
                                [-1, 0, 1], 
                                [-1, 0, 1]]])
curr_filter = conv_filter[0, :]
print(curr_filter)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [78]:
#5,5->3,3
#4,4->2,2
conv_filter1 = np.ones((2,3,3))
conv_filter2 = np.ones((2,3,3))

conv_filter1 = conv_filter1 + conv_filter2
print(conv_filter1)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]
